# serverless.yml

service: stats-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: dist-server/bin/server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
