@startuml "Vincent Farah Test for Seneca"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

Person(api_user, "Web Application User")

Container_Boundary(c1, "stats services solution by Vincent Farah"){   
    Container(web_app, "Web API", "Node Express", "Allows a simple user API")    
    ContainerDb(nosql, "JS cached value", "Nothing at the moment", "Will work with users ephemerally until")   
}

Rel(api_user, web_app, "Uses", "HTTPS")
Rel(web_app, nosql, "Reads from and Writes to", "Cache in JS")

@enduml